# Generated by Django 5.0.4 on 2024-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appestrela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
